-- MySQL Script generated by MySQL Workbench
-- Wed Apr 27 22:42:20 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema figherapi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema figherapi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `figherapi` DEFAULT CHARACTER SET utf8 ;
USE `figherapi` ;

-- -----------------------------------------------------
-- Table `figherapi`.`regina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `figherapi`.`regina` ;

CREATE TABLE IF NOT EXISTS `figherapi`.`regina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `colore` VARCHAR(45) NOT NULL DEFAULT 'Non segnata',
  `data_nascita` DATE NULL DEFAULT (CURDATE()),
  `data_morte` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `figherapi`.`arnia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `figherapi`.`arnia` ;

CREATE TABLE IF NOT EXISTS `figherapi`.`arnia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `luogo` LONGTEXT NOT NULL,
  `ultima_visita` DATETIME NOT NULL DEFAULT (CURDATE()),
  `nota` LONGTEXT NULL,
  `trattamento` LONGTEXT NULL,
  `regina_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_arnia_regina1_idx` (`regina_id` ASC) VISIBLE,
  CONSTRAINT `fk_arnia_regina1`
    FOREIGN KEY (`regina_id`)
    REFERENCES `figherapi`.`regina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `figherapi`.`melario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `figherapi`.`melario` ;

CREATE TABLE IF NOT EXISTS `figherapi`.`melario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `arnia_id` INT NOT NULL,
  `numero_telai_miele` SMALLINT NULL,
  `numero_telai_vuoti` SMALLINT NULL,
  `numero_telai_da_costruire` SMALLINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_melario_arnia1_idx` (`arnia_id` ASC) VISIBLE,
  CONSTRAINT `fk_melario_arnia1`
    FOREIGN KEY (`arnia_id`)
    REFERENCES `figherapi`.`arnia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `figherapi`.`telaio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `figherapi`.`telaio` ;

CREATE TABLE IF NOT EXISTS `figherapi`.`telaio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL DEFAULT 'Vuoto',
  `arnia_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_telaio_arnia1_idx` (`arnia_id` ASC) VISIBLE,
  CONSTRAINT `fk_telaio_arnia1`
    FOREIGN KEY (`arnia_id`)
    REFERENCES `figherapi`.`arnia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `figherapi`.`storico_arnia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `figherapi`.`storico_arnia` ;

CREATE TABLE IF NOT EXISTS `figherapi`.`storico_arnia` (
  `data` DATE NOT NULL DEFAULT (CURDATE()),
  `arnia_id` INT NOT NULL,
  `luogo` LONGTEXT NULL,
  `nota` LONGTEXT NULL,
  `regina_id` INT NOT NULL,
  PRIMARY KEY (`data`, `arnia_id`),
  INDEX `fk_storico_arnia_arnia1_idx` (`arnia_id` ASC) VISIBLE,
  INDEX `fk_storico_arnia_regina1_idx` (`regina_id` ASC) VISIBLE,
  CONSTRAINT `fk_storico_arnia_arnia1`
    FOREIGN KEY (`arnia_id`)
    REFERENCES `figherapi`.`arnia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_storico_arnia_regina1`
    FOREIGN KEY (`regina_id`)
    REFERENCES `figherapi`.`regina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
